package ch.glauser.gestionstock.security;

/**
 * Liste des rôles utilisés dans l'application de gestion de stock.
 */
public enum SecurityRoles {
    PIECE_LECTEUR,
    PIECE_EDITEUR,
    PIECE_STATISTIQUE_LECTEUR,
    PIECE_STATISTIQUE_EDITEUR,
    PIECE_HISTORIQUE_LECTEUR,
    PIECE_HISTORIQUE_EDITEUR,
    IDENTITE_LECTEUR,
    IDENTITE_EDITEUR,
    FOURNISSEUR_LECTEUR,
    FOURNISSEUR_EDITEUR,
    MACHINE_LECTEUR,
    MACHINE_EDITEUR,
    CATEGORIE_LECTEUR,
    CATEGORIE_EDITEUR,
    LOCALITE_LECTEUR,
    LOCALITE_EDITEUR,
    PAYS_LECTEUR,
    PAYS_EDITEUR,
    TECHNIQUE_LECTEUR,
    TECHNIQUE_EDITEUR,
    EXCEPTION_LECTEUR,
    EXCEPTION_EDITEUR
}
