spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_stock
    username: root
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create