spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  batch:
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
    default-schema: public
    drop-first: false
    clear-checksums: false

gestion-stock:
  batch:
    username: gestionstock-batch-user
    password: admin
