spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: false

  batch:
    jdbc:
      initialize-schema: always