spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_stock
    username: root
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

  batch:
    jdbc:
      initialize-schema: always